FROM ubuntu:16.04
MAINTAINER Eduardo Marques <edrdo@dcc.fc.up.pt>

RUN apt-get update && apt-get install  -y \
    automake \
    build-essential \
    make \ 
    curl \
    git \   
    openssh-client \
    openssh-server \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* 
